//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod conversation;
pub mod file_msg;
pub mod group;
pub mod message;
pub mod sea_orm_active_enums;
pub mod user;
pub mod user_group;
